controller_list:
  - name: fake_adele_arm_controller
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_spatula_controller
    type: $(arg execution_type)
    joints:
      - joint_6
initial:  # Define initial robot poses.
  - group: adele_arm
    pose: home